[tool.poetry]
name = "dbt-quickstart"
version = "0.1.0"
description = ""
authors = ["André <andre.soares@altxtech.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
dbt-core = "^1.8.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
